import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../constants";

const { width, height } = Dimensions.get("window");

export const globalStyles = StyleSheet.create({
  // ── Layout ──
  container: { flex: 1, backgroundColor: COLORS.background },
  inner: { padding: 20, paddingTop: 60, paddingBottom: 40 },
  authInner: { flexGrow: 1, justifyContent: "center", padding: 24 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  section: { marginBottom: 28 },
  divider: { height: 1, backgroundColor: COLORS.border },

  // ── Logo ──
  logoWrap: { alignItems: "center", marginBottom: 40 },
  logoImage: { width: width * 0.55, height: height * 0.08 },
  headerLogo: { width: width * 0.35, height: height * 0.06 },
  logoSub: { fontSize: 9, color: COLORS.textMuted, letterSpacing: 3 },
  logo: { fontSize: 28, fontWeight: "900", color: COLORS.text },

  // ── Typography ──
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 8,
  },
  subtitle: { fontSize: 15, color: COLORS.textMuted, marginBottom: 32 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.text,
    marginBottom: 14,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textMuted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 12,
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.primary,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 8,
  },
  urlText: { fontSize: 13, color: COLORS.textMuted, marginBottom: 24 },
  ticker: {
    marginTop: 20,
    fontSize: 11,
    color: COLORS.textFaint,
    textAlign: "center",
  },
  error: {
    color: COLORS.red,
    fontSize: 14,
    marginBottom: 12,
    textAlign: "center",
  },

  // ── Greeting & Hero ──
  greeting: { fontSize: 15, color: COLORS.textMuted, marginBottom: 20 },
  hero: { marginBottom: 28 },
  heroTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: COLORS.text,
    lineHeight: 38,
    marginBottom: 10,
  },
  heroSub: { fontSize: 14, color: COLORS.textMuted, lineHeight: 20 },

  // ── Inputs ──
  inputGroup: { marginBottom: 16 },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textMuted,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 14,
    fontSize: 16,
    color: COLORS.text,
    marginBottom: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textMuted,
    marginBottom: 4,
  },
  form: { gap: 12 },

  // ── Social Grid ──
  socialGrid: { gap: 12, marginBottom: 16 },
  socialField: {},

  // ── Buttons ──
  btnWrap: { marginTop: 8 },
  btn: { borderRadius: 14, padding: 18, alignItems: "center" },
  btnDisabled: { opacity: 0.5 },
  btnText: { color: "#fff", fontSize: 17, fontWeight: "800" },
  switchBtn: { alignItems: "center", marginTop: 16 },
  switchText: { color: COLORS.primary, fontSize: 14 },
  socialBtnGrad: { borderRadius: 14, padding: 16, alignItems: "center" },
  socialBtnText: { color: "#fff", fontSize: 16, fontWeight: "700" },

  // ── Avatar ──
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#fff", fontWeight: "800", fontSize: 14 },

  // ── Tabs ──
  tabs: {
    flexDirection: "row",
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 4,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tab: { flex: 1, paddingVertical: 8, alignItems: "center", borderRadius: 10 },
  tabActive: { backgroundColor: COLORS.primary },
  tabText: { fontSize: 13, color: COLORS.textMuted, fontWeight: "600" },
  tabTextActive: { color: "#fff" },

  // ── Empty / Back ──
  empty: {
    flex: 1,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: { color: COLORS.textMuted, fontSize: 16, marginBottom: 16 },
  back: { marginBottom: 12 },
  backText: { color: COLORS.primary, fontSize: 14, fontWeight: "600" },
  backLink: { color: COLORS.primary, fontSize: 15 },

  // ── Score Ring ──
  ringWrap: { alignItems: "center", marginBottom: 32 },
  scoreRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
  },
  scoreNumber: { fontSize: 44, fontWeight: "900" },
  scoreLabel: { fontSize: 11, color: COLORS.textMuted, fontWeight: "600" },

  // ── Score Cards ──
  cardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 32,
  },
  scoreCard: {
    width: (width - 52) / 2,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  scoreCardIcon: { fontSize: 24, marginBottom: 8 },
  scoreCardValue: { fontSize: 28, fontWeight: "900", marginBottom: 4 },
  scoreCardLabel: { fontSize: 12, color: COLORS.textMuted, fontWeight: "600" },

  // ── Vitals ──
  vitalsCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  vitalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
  },
  vitalLabel: {
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  vitalValue: { fontSize: 26, fontWeight: "900" },
  vitalBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 100 },
  vitalBadgeText: { fontSize: 11, fontWeight: "700" },

  // ── Issues ──
  issueCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
  },
  issueNum: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.primary + "33",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
  },
  issueNumText: { color: COLORS.primary, fontWeight: "800", fontSize: 12 },
  issueText: { flex: 1, color: COLORS.text, fontSize: 14, lineHeight: 20 },

  // ── AI Advisor ──
  aiHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
    gap: 14,
  },
  aiIconWrap: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
  },
  aiIcon: { fontSize: 24 },
  aiTitle: { fontSize: 18, fontWeight: "800", color: COLORS.text },
  aiSubtitle: { fontSize: 13, color: COLORS.purple },
  aiLoading: { alignItems: "center", paddingVertical: 40 },
  aiLoadingText: { color: COLORS.textMuted, marginTop: 16, fontSize: 14 },
  aiError: { paddingVertical: 20 },
  aiContent: { gap: 20 },
  aiCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  aiCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 10,
  },
  aiCardBar: {
    width: 3,
    height: 20,
    borderRadius: 2,
    backgroundColor: COLORS.primary,
  },
  aiCardTitle: { fontSize: 16, fontWeight: "700", color: COLORS.text },
  aiCardText: { fontSize: 14, color: COLORS.textMuted, lineHeight: 22 },
  aiRecCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.purple,
  },
  aiRecNum: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.purple + "33",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    marginTop: 2,
  },
  aiRecNumText: { color: COLORS.purple, fontWeight: "800", fontSize: 12 },
  aiRecText: { flex: 1, color: COLORS.text, fontSize: 14, lineHeight: 20 },

  // ── Settings ──
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 28,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  avatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  avatarLarge: { color: "#fff", fontWeight: "900", fontSize: 20 },
  userInfo: { flex: 1 },
  email: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
  },
  tierBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 100,
  },
  tierText: { fontSize: 12, fontWeight: "700" },
  upgradeCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.primary + "44",
  },
  upgradeTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 4,
  },
  upgradePrice: {
    color: COLORS.primary,
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 8,
  },
  upgradeDesc: { color: COLORS.textMuted, fontSize: 13, lineHeight: 18 },
  linkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  linkText: { color: COLORS.text, fontSize: 15 },
  linkChevron: { color: COLORS.textMuted, fontSize: 16 },
  signOutBtn: {
    marginTop: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.red + "44",
    alignItems: "center",
  },
  signOutText: { color: COLORS.red, fontSize: 15, fontWeight: "700" },
});
